# Generated by Django 5.2.3 on 2025-10-31 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['username'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='codigo_empleado',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código de Empleado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dpi',
            field=models.CharField(blank=True, help_text='Documento Personal de Identificación (13 dígitos)', max_length=13, null=True, unique=True, verbose_name='DPI'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('secretaria', 'Secretaria'), ('vendedor', 'Vendedor')], max_length=50, verbose_name='Rol'),
        ),
    ]
