# Generated by Django 5.2.3 on 2025-11-04 00:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Placa')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=50, verbose_name='Modelo')),
                ('año', models.IntegerField(blank=True, null=True, verbose_name='Año')),
                ('capacidad_carga', models.DecimalField(blank=True, decimal_places=2, help_text='Capacidad en kilogramos', max_digits=10, null=True, verbose_name='Capacidad de Carga (kg)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Camión',
                'verbose_name_plural': 'Camiones',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionCamionRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, help_text='Si está vacío, la asignación está activa', null=True, verbose_name='Fecha de Fin')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_camiones', to='rutas.ruta', verbose_name='Ruta')),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_rutas', to='camiones.camion', verbose_name='Camión')),
            ],
            options={
                'verbose_name': 'Asignación de Camión a Ruta',
                'verbose_name_plural': 'Asignaciones de Camiones a Rutas',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='CargaCamion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Carga')),
                ('hora_carga', models.TimeField(auto_now_add=True, verbose_name='Hora de Carga')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('cerrado', models.BooleanField(default=False, help_text='Si está cerrado, no se pueden agregar más productos', verbose_name='Cerrado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('asignacion_camion_ruta', models.ForeignKey(help_text='Ruta asociada a esta carga', on_delete=django.db.models.deletion.PROTECT, related_name='cargas', to='camiones.asignacioncamionruta', verbose_name='Asignación Camión-Ruta')),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas', to='camiones.camion', verbose_name='Camión')),
            ],
            options={
                'verbose_name': 'Carga de Camión',
                'verbose_name_plural': 'Cargas de Camiones',
                'ordering': ['-fecha', '-hora_carga'],
                'unique_together': {('camion', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='CuadreDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cuadre', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cuadre')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('cuadrado', 'Cuadrado'), ('con_diferencia', 'Con Diferencia')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('carga_camion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuadre', to='camiones.cargacamion', verbose_name='Carga de Camión')),
            ],
            options={
                'verbose_name': 'Cuadre Diario',
                'verbose_name_plural': 'Cuadres Diarios',
                'ordering': ['-fecha_cuadre'],
            },
        ),
        migrations.CreateModel(
            name='CargaCamionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_cargada', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Cargada')),
                ('cantidad_actual', models.DecimalField(decimal_places=2, help_text='Se actualiza con cada venta', max_digits=10, verbose_name='Cantidad Actual')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('carga_camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='camiones.cargacamion', verbose_name='Carga de Camión')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de Carga',
                'verbose_name_plural': 'Detalles de Carga',
                'ordering': ['producto__nombre'],
                'unique_together': {('carga_camion', 'producto')},
            },
        ),
        migrations.CreateModel(
            name='CuadreDiarioDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_cargada', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Cargada')),
                ('cantidad_vendida', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Vendida')),
                ('cantidad_esperada', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Esperada de Retorno')),
                ('cantidad_real_retorno', models.DecimalField(decimal_places=2, help_text='Registrada por secretaria/admin al final del día', max_digits=10, verbose_name='Cantidad Real de Retorno')),
                ('diferencia', models.DecimalField(decimal_places=2, help_text='Positivo = sobrante, Negativo = faltante', max_digits=10, verbose_name='Diferencia')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('cuadre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='camiones.cuadrediario', verbose_name='Cuadre')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de Cuadre',
                'verbose_name_plural': 'Detalles de Cuadre',
                'ordering': ['producto__nombre'],
                'unique_together': {('cuadre', 'producto')},
            },
        ),
    ]
