# Generated by Django 5.2.3 on 2025-10-31 23:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpi', models.CharField(help_text='Documento Personal de Identificación (13 dígitos)', max_length=13, unique=True, validators=[django.core.validators.MinLengthValidator(13)], verbose_name='DPI')),
                ('codigo_empleado', models.CharField(max_length=20, unique=True, verbose_name='Código de Empleado')),
                ('nombre_completo', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('fecha_contratacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Contratación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='vendedores/', verbose_name='Fotografía')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('usuario', models.OneToOneField(limit_choices_to={'rol': 'vendedor'}, on_delete=django.db.models.deletion.CASCADE, related_name='vendedor', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'ordering': ['codigo_empleado'],
            },
        ),
    ]
