# Generated by Django 5.2.3 on 2025-11-04 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignaciones', '0001_initial'),
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha Planificada')),
                ('tipo', models.CharField(choices=[('planificado', 'Planificado'), ('no_planificado', 'No Planificado - Cliente Nuevo')], default='planificado', max_length=20, verbose_name='Tipo de Planificación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones', to='asignaciones.asignacion', verbose_name='Asignación')),
                ('ruta_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones', to='rutas.rutadetalle', verbose_name='Detalle de Ruta')),
            ],
            options={
                'verbose_name': 'Planificación',
                'verbose_name_plural': 'Planificaciones',
                'ordering': ['fecha', 'ruta_detalle__orden_visita'],
            },
        ),
        migrations.CreateModel(
            name='DetallePlanificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitud de Visita')),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitud de Visita')),
                ('fotografia_referencia', models.ImageField(blank=True, null=True, upload_to='visitas/', verbose_name='Fotografía de la Visita')),
                ('hash_foto', models.CharField(blank=True, help_text='MD5 hash para detectar fotos duplicadas', max_length=64, verbose_name='Hash de la Foto')),
                ('foto_duplicada', models.BooleanField(default=False, help_text='Solo visible para administrador', verbose_name='Foto Duplicada')),
                ('ubicacion_valida', models.BooleanField(default=True, help_text='Validada con un margen de 100m. Solo visible para admin/secretaria', verbose_name='Ubicación Válida')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('visitado', 'Visitado'), ('no_visitado', 'No Visitado'), ('cerrado', 'Negocio Cerrado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('hora_llegada', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Llegada')),
                ('hora_salida', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Salida')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('planificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_visita', to='planificacion.planificacion', verbose_name='Planificación')),
            ],
            options={
                'verbose_name': 'Detalle de Planificación',
                'verbose_name_plural': 'Detalles de Planificación',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
