# Generated by Django 5.2.3 on 2025-10-31 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Ruta')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RutaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_visita', models.IntegerField(default=1, help_text='Orden en que debe visitarse al cliente', verbose_name='Orden de Visita')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_asignadas', to='clientes.cliente', verbose_name='Cliente')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='rutas.ruta', verbose_name='Ruta')),
            ],
            options={
                'verbose_name': 'Detalle de Ruta',
                'verbose_name_plural': 'Detalles de Rutas',
                'ordering': ['ruta', 'orden_visita'],
                'unique_together': {('ruta', 'cliente')},
            },
        ),
    ]
