# Generated by Django 5.2.3 on 2025-10-31 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rutas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='rutas.ruta', verbose_name='Ruta')),
                ('vendedor', models.ForeignKey(limit_choices_to={'rol': 'vendedor'}, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_rutas', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
                'ordering': ['-fecha_asignacion'],
                'unique_together': {('ruta', 'vendedor')},
            },
        ),
    ]
