# Generated by Django 5.2.3 on 2025-11-04 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(help_text='Fecha desde la cual comienza la asignación', verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, help_text='Fecha de finalización. Dejar vacío para asignación indefinida.', null=True, verbose_name='Fecha de Fin')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='rutas.ruta', verbose_name='Ruta')),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
                'ordering': ['-fecha_inicio', 'ruta__nombre'],
            },
        ),
    ]
