# Generated by Django 5.2.3 on 2025-11-04 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='vendedor',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'rol': 'vendedor'}, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_rutas', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
        migrations.AddIndex(
            model_name='asignacion',
            index=models.Index(fields=['vendedor', 'fecha_inicio'], name='asignacione_vendedo_69ac2b_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacion',
            index=models.Index(fields=['ruta', 'fecha_inicio'], name='asignacione_ruta_id_4a28eb_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacion',
            index=models.Index(fields=['fecha_inicio', 'fecha_fin'], name='asignacione_fecha_i_adf832_idx'),
        ),
        migrations.AddConstraint(
            model_name='asignacion',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__isnull', True), ('fecha_fin__gte', models.F('fecha_inicio')), _connector='OR'), name='fecha_fin_mayor_que_inicio'),
        ),
    ]
